# Netlify configuration file

# Build settings
[build]
  command = "npm run build" # Ensure this matches your actual build command
  publish = "dist" # Changed from "build" to "dist" which might be your actual output directory

# Headers to handle mixed content
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers - modified to allow HTTP connections
    Content-Security-Policy = "default-src 'self'; connect-src 'self' http://13.232.209.194 http://13.232.209.194:80 http://13.232.209.194:* ws: wss:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Remove upgrade-insecure-requests directive
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    
# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
