# Netlify configuration file

# Build settings
[build]
  publish = "build" # Update this with your actual build output directory (could be "dist", "build", "public", etc.)

# Headers to handle mixed content
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    Content-Security-Policy = "upgrade-insecure-requests; connect-src 'self' http://13.232.209.194:* https://13.232.209.194:* ws: wss:;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
